language: node_js
services:
  - docker
env:
  global:
    - secure: Xpc5oFWGAaLzW+aSSbEzKHKTQD6N5rUvF4T1mRk6ygI4A0ZqPralHPlrFKhJFhcbEH/OBx8VW2BO03hevLy2tNvUpKcyT4eCZPESXJMkzp/bM117ccbRimXYBCU7cqSdtz99ZDg4y0SI0IGdVU0pLQfCkPRhDpoDea1m44IcucLd4OrfvhOUDCmqQuJz2fl0ABqZUKRkZlfSkHCS4PCn+ciow1vQuWxbhWU8Sc+AHmSHMA06kSMxkO3C40skkAyW/P2CpTGmw/qcVtTqw767zXf2J/xYzAUMC4MFeW6A66odOZoLEDCSdh17lLUkymzyRRh97uqduIjJ0fFp3Lqtc6BhkqxvV4Pn8HAkbwOAK1AbQx7QjEULdkM6/IrM1msgzrt81aJmK0BUkDE0woTib8xPe+zStgfGBSzwvnNaaPy5rY+6z7zLEopq0HvUBUe81ubRUIcX5td0geA+w634D0hikJVraCNmqeiyPh6xHvCqkHexKTD4WxD34+ugkSPze2NYz1L0PMBE8tKmNpcpyOpfDLKmyNjc4TCC1LnB3pZwGU2FsWBnxTkqmJmaR53U+Y/II5bBWlbJtnC7mmI0SglCnpRb3NBpL3WtlWVl0uE5p658SXCc2LrFPcCnzLwAJlTPXHw3rbU0rvJpgqOzOpeycNjG3N1kpHQLxCjf6Os=
    - secure: sVsZP6ziqFYNTRC/etDr/Vj1CscEOoEfMAoTO4tyrdHDJtETbMPFfVxeB663ne+aBtBdj+03xDNE+O0ZwO26cQFe+UFIsWfZiyqWrm79TvI1FHW18XjK/CwHNUnf88/M5XU859diY4/dDr4wwOjp6Fid5Bbbmq+wR3EeJcOFxwFwcaDHgG4wS7OFg3FzR59ZO8IFypotbdp/qZwa2T6no4Ni8V2vxh/MUQtc213eHRkORhGYXXGLOVc5hjpzTF23o+aNO3pVu1jjOrP1A0hbBKBuCtEAmbVbwfo5zy0df2uX9BRBe4Al3jlM7BJwW9N2BmrD9DS5pbNnZ/ArXVjj2vph5qjyCuvibggngfaMa6ruzZZ4Z9eNKMex0SNRoFWj8qyzKEXRPD4c/A4p5IoBPyExydWXBDoyFEn7MPLVSV6TOvpzKalWSBzyAJgj5pKrbQWxrlBnoaI1aApfABFP2ViekSU/YzpuzJl2qCldgCPNiSbEFoGYilh3RKOfllfF8nSNdqiWfU7EbG+cSR6L6lo5qSjopgmmoN1/ClR+d3b+wxzMDiZifAkkMFQrACvjlILVje2Q/BTzzMyBf+/90WtApNgyFjHpGMmyugc5riulTQAVthM/0qVxXtZPFfFnMI8769sokNT+L0wH5vmQc1VAeh/FhM3yzBwiTN0QZv4=
    - IMAGE: jonaskay/bindery-compositor
install:
  - docker build -t $IMAGE .
script:
  - docker run -it --entrypoint /bin/bash $IMAGE -c "yarn test"
deploy:
  provider: script
  script: ./publish
  on:
    branch: master
